### ISSUE TITLE
Fix flakiness, again..

### ISSUE THREAD

**Issue by vkottler** [vkottler/vtelem#31]
Got this unit test failure:

```
INFO     vtelem.channel.environment:environment.py:235 1000.000: 21 emits, 3 events, 6 frames
WARNING  vtelem.classes.type_primitive:type_primitive.py:71 value '-1' not valid for type 'Primitive.UINT16'
INFO     vtelem.daemon:__init__.py:97 frames     - Thu Jan  1 00:00:00 1970: running -> idle
=============================== warnings summary ===============================
tests/stream/test_writer.py::test_stream_writer_file
  /home/runner/work/vtelem/vtelem/venv3.8/lib/python3.8/site-packages/_pytest/threadexception.py:73: PytestUnhandledThreadExceptionWarning: Exception in thread frames
  
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "/home/runner/work/vtelem/vtelem/vtelem/daemon/__init__.py", line 244, in run_harness
      self.run(*args, **kwargs)
    File "/home/runner/work/vtelem/vtelem/vtelem/daemon/queue.py", line 51, in run
      elem = self.queue.get()
    File "/home/runner/work/vtelem/vtelem/vtelem/classes/metered_queue.py", line 49, in get
      self.env.metric_add(f"{self.name}.elements", -1, time)
    File "/home/runner/work/vtelem/vtelem/vtelem/channel/environment.py", line 160, in metric_add
      assert chan.add(data, time)
  AssertionError
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

---------- coverage: platform linux, python 3.8.12-final-0 -----------
Coverage HTML written to dir htmlcov
Coverage XML written to file coverage.xml

=========================== short test summary info ============================
FAILED tests/stream/test_writer.py::test_stream_writer_file - AssertionError
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
============= 1 failed, 78 passed, 1 warning in 114.18s (0:01:54) ==============
Command exited with non-zero status 1
real 114.60
user 43.13
make: Leaving directory '/home/runner/work/vtelem/vtelem'
sys 0.73
make: *** [/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/vmklib/data/python.mk:54: python-test] Error 1
```

We sometimes also still get the infinitely-running unit tests. Is that possibly the command-line invocation not timing out?

**Comment by vkottler** [comment]
Also this:
```
tests/stream/test_writer.py::test_stream_writer_file 
-------------------------------- live log call ---------------------------------
INFO     vtelem.frame.framer:framer.py:61 using application identifier '32767'
DEBUG    vtelem.registry.enum:enum.py:89 enum 'frame_type' already registered as 0
DEBUG    vtelem.registry.enum:enum.py:89 enum 'message_type' already registered as 1
DEBUG    vtelem.registry.enum:enum.py:89 enum 'frame_type' already registered as 0
DEBUG    vtelem.registry.enum:enum.py:89 enum 'message_type' already registered as 1
DEBUG    vtelem.registry.enum:enum.py:89 enum 'daemon_state' already registered as 2
INFO     vtelem.daemon:__init__.py:97 frames     - Thu Jan  1 00:00:00 1970: error -> idle
INFO     vtelem.daemon:__init__.py:97 frames     - Thu Jan  1 00:00:00 1970: idle -> starting
INFO     vtelem.daemon:__init__.py:97 frames     - Thu Jan  1 00:00:00 1970: starting -> running
INFO     vtelem.channel.environment:environment.py:235 10.000: 20 emits, 29 events, 31 frames
INFO     vtelem.channel.environment:environment.py:235 20.000: 21 emits, 4 events, 7 frames
INFO     vtelem.channel.environment:environment.py:235 30.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 40.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 50.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 60.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 70.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 80.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 90.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 100.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 110.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 120.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 130.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 140.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 150.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 160.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 170.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 180.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 190.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 200.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 210.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 220.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 230.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 240.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 250.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 260.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 270.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 280.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 290.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 300.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 310.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 320.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 330.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 340.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 350.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 360.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 370.000: 21 emits, 3 events, 6 frames
INFO     vtelem.channel.environment:environment.py:235 380.000: 21 emits, 3 events, 6 frames
WARNING  vtelem.classes.type_primitive:type_primitive.py:71 value '-1' not valid for type 'Primitive.UINT16'
INFO     vtelem.channel.environment:environment.py:235 390.000: 21 emits, 3 events, 6 frames
INFO     vtelem.daemon:__init__.py:97 frames     - Thu Jan  1 00:00:00 1970: running -> idle
INFO     vtelem.channel.environment:environment.py:235 400.000: 21 emits, 3 events, 6 frames
```

**Comment by vkottler** [comment]
https://github.com/vkottler/vtelem/commit/ac336101a17a678f8e97ec9abfd8fa1279dc87fc

We had to set `flush` to `True` when writing, otherwise it was hanging for some reason
